name = "Walrus"
uuid = "bec5164f-1c7a-4c32-8768-be9354254d6a"
authors = ["Jago Stong-Wright <jagoosw@protonmail.com>"]
version = "0.1.0"

[deps]
Oceananigans = "9e8cae18-63c1-5223-a75c-80ca9d6e9a09"
Roots = "f2b01f46-fcfa-551c-844a-d8ac1e96c665"

[compats]
Oceananigans = "0.90"
